# 五胡乱华

在西方日耳曼入侵（公元4世纪左右）发生的同时，东方也发生了一起北方蛮族入侵事件，那就是五胡乱中华。

话说东汉末年分三国，战火连绵不休，好不容易三分归晋，又来个八王之乱。打仗是会死很多人的。以长安为例，王莽之乱之后，长安破败，汉光武帝刘秀定都洛阳，史称东汉。经过东汉的修养，长安又重归繁荣，于是董卓一把火烧了洛阳，又迁都长安。吕布杀董卓，死了很多人；李傕逐吕布，又死了很多人。

这里介绍一个三国时期的牛人——贾诩。一说三国的聪明人，大家都知道卧龙凤雏，或者曹操司马懿，或者赤壁周郎周公瑾。而这个贾诩，说实话一点都不比他们差。他最大的成就，就是一语亡国。一句话，毁了汉朝三百年国祚。话说吕布武力虽强，但在董卓的部队里面地位其实不是很高，相当于总司令的警卫团团长而已，而董卓部下的王牌军，都是在李傕郭汜掌握下。当吕布作乱杀了董卓后，李傕郭汜等人都畏罪潜逃，准备跑回西凉老家。路上就碰到贾诩了。贾诩问：“将军这是去哪里啊？”李傕回答：“董司令已经被司徒王允和吕布杀了，下一个估计就要来杀我们了，所以赶紧逃吧！”贾诩说：“将军一个人跑回老家，路上随便一个乡长就能把你抓了，押送回来杀头，哪里回得了老家？但是将军手下几个军的兵力，整顿一下杀回长安，吕布一个警卫团哪里抵挡得住？天子长安不是尽在掌握之中。”就这一句话，汉朝彻底亡了。

李傕觉得有道理，带兵杀了，驱逐吕布，斩杀王允，长安又死了很多人。之后李傕郭汜又反目，又杀了很多人，逼得汉献帝出逃，被曹操接走。曹操收回长安后，又与西北马家军起冲突，于是马超带兵一路杀到长安，杀得曹操割须弃袍，又死了很多人。随后曹操杀了回来击败马超，又收回长安，又死了很多人。虽然之后的三国长安不再有战火，但是魏蜀之间的战争，都在长安附近。先是曹操平张鲁在汉中，随后黄忠斩夏侯渊于定军山，诸葛亮六出祁山，姜维九伐中原，都是在长安附近打的战，长安都要出士兵出脚夫保障后勤供应，同样会造成人口的减少。人口减少，自然会有新的人口迁移进来，汉人少了，就只能迁胡人进来。晋惠帝元康九年（公元299年），太子洗马陈留江统作《徙戎论》提醒朝廷说，关中人口百万，胡人占了一半（《资治通鉴》第八十三卷）。

整个中国北方也处处可见胡人。按当时的观念，若论亲疏，当然汉人才是自己人。而打仗是要死人的，让自己人去死，当然不如让外人去死。因此对于统治阶级而言，让汉人去打仗，就不如用胡人去打仗。当年汉元帝把南匈奴安置在河套地区，就是用来抵挡北匈奴的，以夷制夷嘛。本来一开始还是让汉人去当统帅，后来发现还是直接让胡人当统帅效果更好，于是很多胡人都受到重用。例如并州（现山西省）的匈奴刘渊（这时候很多胡人也在汉化，其父刘豹已经起汉名了。由于冒顿单于娶了刘邦的宗室之女，所以他们自认为汉室刘家的外孙，也取汉姓刘。），后来当到了宁朔将军，监五部军事。朔，本来指的是北方，后来主要指河套地区，汉武帝赶走匈奴后在这里设了朔方郡。宁朔将军，就是朔这个地方的安宁就你负责了。五部，就是当年曹操将南匈奴分化管理，分为左右南北中五部，每部都设置有统帅，并以汉人监管。现在都让刘渊一个人一起监了。你们胡人负责打仗，我们汉人负责享福，估计这是当时很多汉人统治者的想法。虽然对外战争重用胡人效果很好，但是渐渐的，胡人也掌握了军权，内附的胡人也渐渐变成了一种内患。不过只要汉人团结，还是可以控制住胡人的，但是如果不团结，例如西晋的八王之乱，那就hold不住胡人了。

八王之乱，就是司马家八个王通过武力轮流掌权，自相残杀得是不亦乐乎，将中国北方毁得不堪入目。你汉人不团结，就别怪我胡人追求独立自主了。于是公元304年，刘渊揭竿而起。他不是认为自己是汉室刘家的外孙吗？好吧，那建立的国家就叫“汉”好了，史称匈奴汉国。当时距离东汉禅魏（公元220年）才80多年，期间还有个举着“汉”旗的蜀汉政权，因此匈奴人刘渊托“汉”之名很有利于团结胡汉双方的人才，获得胡汉双方百姓的支持。于是匈奴汉国发展很快，最终成功把西晋打趴下，成为北方一霸。

后来匈奴汉国内乱，刘渊养子刘曜平乱后登基。可能觉得没必要再给汉人装孙子了吧，于是在公元318年更改国号。由于匈奴刘家起家于平阳，位于今天的山西南部地区（临汾附近），战国时期属于赵国，因此改国号为“赵”。毕竟都是匈奴刘家建的国，于是统称为“汉赵”，又区别于石勒的赵国，于是也叫“前赵”。
 
图7 汉赵疆域图（公元317年）

这就是五胡乱华的第一胡——匈奴。（其他匈奴）
顺便说一下。晋朝是一个统一的王朝，八王之乱主要发生在北方，后来晋愍帝司马邺降汉之后，南方的汉人贵族不同意投降，于是拥立琅琊王司马睿为皇帝，定都建康（现南京），继承大统，史称东晋。曾经有部根据小说改编的电视剧《琅琊榜》，就跟这个背景有关系。

而五胡中的第二胡，就是羯。
话说羯族，有明显的白种人特征，深目高鼻多须，他们其实也是匈奴的奴，不知道匈奴在打中亚哪里的时候抓到的俘虏，带着自己的特色一直跟着匈奴混，也被称为“匈奴别部”，随着匈奴一起迁入中原。

羯族的代表就是石勒。要说当过皇帝的人的起点，朱元璋就够低的了，朱元璋是当过和尚当过乞丐，而这石勒这是中国史上唯一一个从奴隶起家的皇帝，可见他奋斗的艰辛。他一开始自己混，混得有点资本了就入股刘渊的匈奴汉国，而当刘渊养子刘曜平乱后自立为王时，跟石勒没处好，于是石勒就自立门户。由于他实际占据了古代赵国的统治地区，于是在公元319年自称大将军、大单于、领冀州牧、赵王，于襄国即赵王位。由于立得比刘曜的“赵”晚，又持续得长，于是史称“后赵”。石勒在几乎占领整个中国北方后，于公元330年正式称帝。石勒的后赵势力已经南侵到江夏合肥，围困过湖北襄阳，盘算着江陵武汉，这里已经算中国的南方了。
 
图 8 后赵疆域图

石勒死后，他侄子石虎独揽朝政，第二年就篡了石勒儿子的皇位。这石虎的残暴是史上留名的。石虎的太子石邃一直跟着他爸征战四方，灭前赵就有他的功劳，石虎很喜欢他。石虎还经常跟大臣们说：“司马氏父子兄弟自相残杀，所以朕得以有今天。而朕岂有杀石邃的道理呢！”后来，父子有隙，于是石虎把石邃杀了，“及其妃张氏，并男女二十六人同埋于一棺”（《资治通鉴》第九十五卷）。

这段时间，历史称为东晋十六国，或者五胡十六国。故事并不是单一的一个西晋，崛起个汉赵顶替西晋，再崛起个后赵顶替汉赵。在这条故事线发生的同时，好多个其他胡也在崛起，如五胡中的第三胡——氐。

氐族分布在今甘肃、陕西、四川等省的交界处，大部分集中于陇南地区，早在西周时期属于西戎的一部，到了春秋战国时期开始以氐作为族称。虽然氐族也在崛起，但是当不了老大。西晋末年，略阳（属陕西省汉中市）氐族推出贵族苻洪为小头头。一开始跟着刘家混，前赵刘曜在长安称帝时，封苻洪为氐王。后来石勒把前赵灭了，苻洪又跟着石家混。公元333年，石虎让苻洪当流民都督，带领关中豪杰与各种胡人搬家到关东的枋头（今河南省鹤壁市浚县）。强制搬迁，大家心里肯定不乐意。于是石虎一死（公元349年），苻洪就投降了东晋，第二年350年，苻洪在枋头就自称大都督、大将军、大单于、三秦王。不久苻洪被石虎旧将麻秋毒死，其子苻健继位。苻健大喊：“我要带你们回家！”，于是自枋头而西，直入长安，据有关陇。351年，苻健自称大秦天王、大单于。352年，改称皇帝，国号秦，史称前秦。
苻健死后，其子苻生继位，这又是一个出了名的残暴之主。有一次找人过来问，“我这皇帝当得怎么样啊？你在外面听说些什么啊？”多好的拍马屁的机会啊，于是有人赶紧回答：“圣明宰世，赏罚明当，天下唯歌太平。”苻生说：“你谄媚我！”于是拉出去斩了。过了几天又找人问，“我这皇帝当得怎么样啊？”前两天才发生的事情，你还来！于是大家不敢拍马屁了，有人就回答：“陛下判刑处罚还是有一点点过了的。”苻生说：“你诽谤我！” 于是拉出去斩了。这是没事找事鸡蛋里挑刺，想着借口杀人。于是“勋旧亲戚，诛之殆尽。”（《资治通鉴》第一百卷）

这种事情发生多了，难免大家会想：“照这么杀下去，早晚轮到我。”这样想的人多了，难免会有一伙人想：“等你杀我，不如我杀你，先下手为强。”这样想的人多了，难免有人就真动手了。于是，苻家最闪亮的男神登场了，时任龙骧将军的东海王苻坚带人杀入宫中干掉了苻生。苻坚和苻生是同一个爷爷，就是三秦王苻洪，他也是有资格继承皇位的。
苻坚继位后，重用宰相王猛，励精图治，终于在公元376年再次统一了中国北方，距离开始分裂的八王之乱（291年）已经过去85年。于是又过了6年，公元382年十月，苻坚召集群臣，提出亲率百万大军一举灭晋，实现中国统一。于是发生接下来的淝水之战。
 
图9 前秦疆域图

一方面，东晋，多年来一直没怎么雄起，偏安东南，说自己是正统都有点不好意思了。总指挥谢安清点了一下兵力，就八万人马，还不够前秦的十分之一。那硬着头皮也得上啊，毕竟人家打到家门口了。于是前线指挥谢玄带着人马来到淝水东岸与苻坚对峙。

另一方面，前秦，虽号称百万大军，但却不是铁板一块。苻坚倒是希望有清一色的百万氐人军队，但氐人哪有那个人口基数。所以构成这百万大军的，是各色人种都有。汉人匈奴羯人，应有尽有。北方统一才6年，可分裂了近百年，还加入了很多外来民族，民族融合完全处于一种马赛克的状态，完全没法融合。你能指望这一百万人同心协力？肯定是各怀鬼胎，伺机而动。所以当苻坚提出要南征的时候，阳平公苻融就说：“东晋虽然没雄起，但是也好好的，没啥内患。人家上下一心，也不好打。反倒是我们统一北方时被我们灭掉的各个胡人政权，政权是没了，但是人还在，心还不死，而且布满京师，那才是我们的心腹大患。把他们消化掉才是最重要的。当年丞相王猛临死前也是这么说的啊！”苻坚不听，一定要带着这百衲衣般的百万大军，南下东晋，来到淝水西岸。

这两边都压在河边，都想等对方半渡而击，都不动。于是谢玄派人跟苻坚说：“你来都来了，咱就扯开膀子干一战吧。你压在河边我过不去，你往后退退，我过来跟你一决雌雄。”
苻坚说：“好！看你过来我怎么干你。传令下去，往后退退。”

一百万，那是多大一个数字！排成方阵，前面死光了后面都看不见什么情况。

苻坚说往后退退，A听了对后面B说：往后退退，让那边晋军过来。

B对后面C说：往后退退，那边晋军要过来。

C对后面D说：往后退退，那边晋军要过来了。

D对后面E说：快往后退退，那边晋军过来了。

E对后面F说：赶紧往后退，晋军过来了。

F对后面G说：赶紧往后撤，晋军杀过来了！

再往后传，就更离谱了。反正，完全失控了。到了最后成了：赶紧逃命吧，晋军杀过来啦！我们败啦！

就这样，百万大军做雪崩状，兵败如山倒，任你苻坚再英明神武也阻止不了。苻坚逃回洛阳时，就只剩十余万惊弓之鸟了。苻坚怎么想也想不明白，怎么好好的传一句话就传败了呢？
淝水之战（公元383年），跟三国赤壁之战（公元208年）很像，都是经历了近百年分裂之后，北方政权尝试再次统一中国，而且两次都在绝对优势的情况下被以少胜多，未能成功统一中国。赤壁之战失败了，实现统一的愿望又等了近百年，好不容易等来西晋灭东吴（公元280年），却只有短短10年的西晋统一。而淝水之战失败了，实现统一的愿望又等200年，才等来隋朝灭南陈（公元589年）。如果不算短命西晋，从公元189年董卓进京开始乱政，地方诸侯各自起兵逐鹿中原，中国开始进入分裂，一直到公元589年隋朝灭南陈，中国整整经历了400年的分裂。

苻坚一败，那一块块马赛克就都又活跃起来了，其中就有第四胡——羌。
羌族其实也是西戎的一支，主要分布在西北，陕西甘肃四川都有。在先秦史籍中往往氐羌连用或并称，而羌比氐出名，毕竟现在还有羌族，但已经没有氐族了。先秦人甚至认为氐人是生活在氐地的羌人，但又觉得氐和羌略有区别，因此称氐为氐羌。羌族对汉朝而言也是一个外患，收拾完匈奴后，主要就是对付西北羌族了。其中最有成绩的应该算是伏波将军马援了，也就是三国马超的祖先，让羌族人很信服，马家在西北是很有声望的。

到了西晋末年，北方大乱，世代为羌族酋长的姚家也带着羌族兄弟们起来追求独立自主，不过也没怎么成大气候。后来姚襄在与前秦交战时被俘杀，他弟弟姚苌（cháng）率部降于前秦。苻坚继位后，姚苌多次立功，很受苻坚喜欢。喜欢到什么程度呢？话说快打淝水之战的时候，苻坚把姚苌叫过来，说：“你之前干的不错，这次打东晋你要好好努力哦！你知道我当皇帝之前是什么官职吗？是龙骧将军！皇帝这个位置是不能给你的，但是，我可以封你为龙骧将军！这个官职我可是从来没有让别人当过哦！我很看好你吧！好好干哦！”好吧，你让他好好干，沿着你的脚印走好吧？现在你让他跟你一样当龙骧将军，下一步你想让他跟你一样当什么？也不知道是庆幸还是不幸，反正姚苌不负苻坚所望，淝水之战后想清楚了，就真反了自己当皇帝。公元384年，姚苌在渭北马牧，被羌民和西州豪族推为盟主，称大将军、大单于、万年秦王，史称后秦。公元385年，姚苌围擒出逃的苻坚，后将苻坚缢杀。公元386年四月，正式称帝，建都长安。
 
图10 后秦疆域图（中间淡紫色区域）

从疆域图中也可以看出来，后秦崛起得也不咋的，最后还让东晋给灭了。说实话东晋没灭过几个国家。不过后秦也是遇上猛人了，因为这位东晋的猛人不止灭了后秦，还灭了东晋，这就是南朝宋国开国皇帝刘裕。

而跟着姚苌一起活跃起来的，还有最后一胡——鲜卑。
鲜卑这个词现在对很多人而言已经很陌生了，但其实很多人经常听到和鲜卑同义的一个词，只是我们不知道说的就是鲜卑。每到冬天，天气预报经常讲，又有一股冷空气，从鲜卑利亚，吹向我们北方地区。这个鲜卑利亚是哪里？对，就是西伯利亚（Siberia）。鲜卑利亚，就是鲜卑人的土地的意思，是鲜卑人的发源地。

当年匈奴崛起的时候，匈奴东面还有一群胡人，被称为东胡。匈奴冒顿单于开挂，把东胡打得差不多了，除了死的降的，剩下的就跑到两座山上去躲了起来。这两座山一座在大兴安岭南端，叫乌桓（又叫乌丸）；一座在大兴安岭北端，叫鲜卑。乌桓比较靠南，在汉朝打败匈奴之后还出来蹦跶了一下，让曹操给灭了。而鲜卑则在匈奴西迁之后，主要在北方抢地盘，靠南的几个部族也随着其他几胡一起来乱中华。

鲜卑族分为几个部族，有段氏，宇文氏，拓跋氏，慕容氏。
慕容鲜卑，在乱华的时候就建立了各种燕国。先是慕容皝（huàng）在龙城（今辽宁朝阳）建立前燕，后来慕容家又建立了后燕、西燕、南燕（北燕是鲜卑化的汉人冯跋扶持后燕慜帝慕容宝的养子慕容云（高句丽人高云）建立的，后冯跋自己称帝）。《天龙八部》里面的姑苏慕容复一心想复国的燕国，就是这个燕。

鲜卑族，史书上的描述是：赤髯碧眼老鲜卑。《晋书》将鲜卑人称为黄头黄须。在西晋时期有“白奴”之称，苻坚也怒称他们为“白虏”，可见他们是白种人，金发碧眼白皮肤的高加索人种。所谓一白遮百丑，长得白净自然惹人喜欢，要是再五官端正，身材高窕，那真是没说了。前燕皇子慕容冲姐弟俩就长得非常秀美，于是苻坚灭了前燕后，将这姐弟俩都收入后宫，••••••（此处删去儿童不宜的***字）。因此苻坚淝水之战失败后，慕容家又复辟。慕容垂在荥阳（今河南荥阳）复称燕王，建立后燕。慕容泓在关中向长安进军，改年号为燕兴，建立西燕。那个美男慕容冲接了慕容泓的班，把长安死死围住，逼跑了苻坚（苻坚跑出去后就被姚苌抓了），灭了前秦。

这是慕容鲜卑，另一个厉害的鲜卑，则是拓跋鲜卑。这是五胡终结者，要介绍拓跋鲜卑，得另起一章了。

另外，这里介绍一个词——可汗（Khagan），也翻译为汗（Khan），为了表示强大也叫大汗，为跟汉文化融合也叫汗王。这个称呼最早被用于称呼鲜卑部落的酋长，不同于匈奴的单于。五胡乱华时，各个强者强大到一定程度都会担任“大单于”的官职，包括鲜卑的慕容皝。毕竟鲜卑也跟匈奴混过嘛，学学人家很正常，就像他们最后登顶的时候都是担任“皇帝”一样，跟汉人学的。但是有一支慕容鲜卑，带头的叫慕容吐谷浑（tǔ yù hún），因为在老家（现辽宁省东部）混不下去，就带着自己的小弟们，在公元283年西迁到今内蒙古自治区阴山地区。公元313年左右，又从阴山南下，至陇西枹罕（今甘肃省临夏），以此为根据地，向南、北、西三面拓展，统治今青海省、甘肃省南部、四川省西北等地，这就是后来的吐谷浑汗国（从图7到图10，地图西侧一直有个吐谷浑汗国）。因为没在中原跟大家一起玩，没学到，也不好意思用一些高大上的词汇，所以他们的领袖一直以可汗自称。而在中原，随着鲜卑族的崛起，自我认同感和民族自豪感的提升，后来就渐渐以“可汗”为傲，以“可汗”自称，而不再使用匈奴的“单于”称呼了。





