# 突厥

话说柔然看到北魏分裂，自我感觉行情走好，牛市很快就要来了，没想到牛市属于别人。从背后又杀出一个打铁的小弟，从背后捅了自己一刀，这就是突厥。

根据唐朝长孙无忌撰写的《隋书》（84卷）记载，突厥的祖先是平凉地区的杂胡，姓阿史那，后来北魏统一北方时被清扫了，于是投靠柔然，给柔然打铁，被安排在于金山（今阿尔泰山，在新疆北端，蒙古西部）南麓。因为金山的形状像一个战盔“兜鍪”（dōu móu），俗称突厥，因此这个部落就以突厥为名。金山这片地区居住着柔然治下的铁勒人（中国古代北方、西北方民族，又称狄历、丁零、敕勒、高车。），因此迁到金山后的突厥人逐渐跟该地区的铁勒人融合，被铁勒化了。后来突厥部落崛起，人数增多，多数人来源于周围的铁勒部落，所有铁勒后裔也就改称为突厥了。他们主要是高加索人种。
 
图16 阿尔泰山

公元552年突厥大败柔然，阿史那土门称伊利可汗，建立突厥汗国。最盛时疆域东至辽海（辽河上游）， 西濒里海，北至北海（今贝加尔湖）， 南临阿姆河南。
 
图17 突厥疆域图

值得一提的是，之前的柔然是没有自己文字的，因此在跟南朝眉来眼去的时候互通的文书都是使用汉字，由汉人代笔，而突厥于公元5世纪就已经发明了自己的文字。于是有很多东西就能多方印证了。例如阿尔泰山以西有一群人，叫嚈哒（yàn dā），又叫白匈奴，其政治中心在现在阿富汗巴尔赫地区，这个国家虽然没城镇没文字，但是也曾雄极一时。再往西是萨珊波斯，再往西就是拜占庭（东罗马帝国）了（见图18）。于是突厥勾结萨珊波斯，东西夹击，把嚈哒给灭了（见图19）。然后，突厥又和拜占庭勾结，东西夹击，对抗萨珊波斯，不过这次没能把萨珊波斯给灭了。所以突厥跟中西亚文明已经有了很多交集了。这是突厥往西的发展。
 
图18 嚈哒波斯拜占庭的位置（中国为北魏和南齐）
 
图19 突厥波斯拜占庭的位置（来自百度图片）

往东，突厥把柔然的家底全部收为己有，同时当然也包括东西魏和后来的北周北齐每年示好的岁贡。581年杨坚代周，建立隋朝。此前北周已经消灭北齐统一了北方，因此局面又回到当年北魏-柔然的格局，因此停止向突厥的岁贡。那突厥肯定想：你不给我钱，我就打你！于是隋朝跟突厥正式开战。

在那个年代，通信交通很不发达，因此维持一个大领土的国家很不容易。首都发一份政令到边疆，边疆官吏拿到政令时，可能已经过时效了。边疆如果发生暴动，消息传到中央，中央再动员组织平乱部队，等部队出发抵达边疆时，黄花菜都凉了。因此为了方便管理，不得不给地方赋予一定的自治权。在中国的周朝和西欧的日耳曼王国，大家使用封建制，就是在确保一个中心的前提下，给予地方充分自治权。但随着地方势力膨胀，甚至超过中央时，就会出现郑庄公射周桓王和法国国王政令不出巴黎的现象。这种情况的下一步发展就很容易演变成群雄逐鹿，旧中心不行了，争取再打出一个新中心来。而另一种办法，就是为了保证中央集权，有些国家采用的多王共治。例如罗马就出现过两个奥古斯都和两个凯撒的情况，相当于两个正皇帝加两个副皇帝。但是这种情况的下一步发展就很容易演变成分裂，例如罗马就分裂成东罗马和西罗马。

突厥也一样，地盘太大了，管不过来。于是在公元580年，突厥在西域设立小可汗，统管阿尔泰山以西的地区。公元583年，突厥汗国分裂成东突厥、西突厥两部。
 
图20 东西突厥分裂

尽管分成两部，东突厥还是很有战斗力的，对隋朝边境造成重大压力。明的不行就来阴的。于是杨坚封东突厥的一个小头目突利为启民可汗，支持他反叛东突厥，并在河套地区让他建国，以抵挡东突厥的进攻，就像当年汉元帝把南匈奴放在河套地区抵挡北匈奴的进攻一样。借这个机会杨坚抓紧时间统一了中国，结束了400年的分裂，而后来启民可汗也成功接手东突厥。本来这样隋朝跟东突厥应该关系很好，一起抵抗西突厥的才对。可是随着东突厥的实力增大，隋朝又担心了，几个来回关系没处好，掰了。

公元615年，隋炀帝杨广巡狩北塞（当时已经隋末，三征高丽已经都失败了，很多地方已经揭竿而起了），被突厥始毕可汗突袭，杨广躲进了雁门郡城。雁门郡41座城池中有39座被突厥攻克，仅剩下雁门和崞（guō）两城。城中粮食只够吃20天。突厥人的箭都射到了杨广御驾之前，吓得杨广抱着儿子直哭（《资治通鉴》第一百八十二卷），可以想象一下当时杨广心里得多害怕。

后来隋末天下大乱，而东突厥在始毕可汗的统治下越来越强大，周边的其他小部落都成为附庸，而在中原逐鹿的各路英雄，也纷纷对突厥称臣。（《新唐书》列传第一百四十上：“隋大业之乱，始毕可汗咄吉嗣立，华人多往依之，契丹、室韦、吐谷浑、高昌皆役属，窦建德、薛举、刘武周、梁师都、李轨、王世充等倔起虎视，悉臣尊之。控弦且百万，戎狄炽强，古未有也。”）就连唐高祖李渊起兵的时候，也得讨好突厥。
不过随着唐朝再次统一，国力重新恢复，像汉武帝北击匈奴一样，唐太宗也开始算旧账了。
公元629年（贞观三年）秋，唐太宗命李靖（不是托塔李天王）率李勣、柴绍、薛万彻，统兵10万，分道出击大败突厥，东突厥灭亡。慑于大唐天威，“四夷君长诣阙请上（唐太宗）为天可汗”（《资治通鉴》第一百九十三卷）。

唐太宗李世民收拾了东突厥，他儿子李治就出手收拾西突厥。公元657年（唐显庆二年）春，唐朝派出两路人马向西突厥进发，北路右屯卫将军苏定方负责武装打击，南路右卫大将军阿史那弥射（当年投降唐太宗的西突厥酋长）负责招降纳叛。苏定方军在曳咥河（今喀喇额尔齐斯河）西大败西突厥全部家底十万骑兵，然后秋风扫落叶般一路高歌，西突厥国亡。
突厥作为一个大家庭，这就散伙了，于是各部族就分家了，你回你的流沙河，我回我的高老庄，各自找出路吧。

因此很多部族也开始像匈奴柔然一样西迁了。不过当年匈奴和柔然是从里海北边走，走过西西伯利亚平原，跨过乌拉尔山脉，穿过东欧平原进入中欧。但是西突厥紧挨着中西亚，跟很多中西亚文明有交流，例如萨珊波斯帝国，阿拉伯帝国，拜占庭帝国。因此突厥西迁时是从里海南边走的，进入中西亚，现在哈萨克斯坦、吉尔吉斯斯坦、乌兹别克斯坦、土库曼斯坦等中亚国家都自称为突厥人的后裔。

突厥人西迁的时候刚好遇到阿拉伯帝国崛起。阿拉伯人手持大弯刀，高举新月旗，从圣地麦加出发，四处传播伊斯兰文明，东灭两河流域的萨珊波斯，南占尼罗河畔的埃及，西侵北非的迦太基和伊比利亚的西哥特王国，北却小亚细亚的拜占庭，建立了继罗马帝国之后再一个横跨亚非欧的大帝国（欧洲只占了伊比利亚半岛，没能拿下法国）。因此西迁入阿拉伯帝国的突厥人也开始皈依伊斯兰教，并且作为雇佣兵加入了新月旗的征战。
 
图21 阿拉伯帝国

打仗，就有机会立功，立功就能得到封赏，有了封赏就开始有了领地，有了领地就可以建立自己的王国。于是各种大大小小的突厥苏丹国（sultanate）得以建立，其中有一个叫塞尔柱的更是做大做强，做到了塞尔柱帝国的程度。

其实，由可汗（Khagan或者Khan）统治的国家应该叫汗国（khaganate或者khanate），由公爵（duke）统治的国家应该叫公国（duchy），由国王（king）统治的国家应该叫王国（kingdom），由皇帝（emperor）统治的国家才叫帝国（empire）。有时某些人实在太强大了，不是皇帝也被我们称为大帝；有时某些国家实在太强大了，没有皇帝也会被我们称为帝国。例如马其顿国王亚历山大大帝（Alexander the Great，扑克牌的梅花K）建立的马其顿帝国，其实应该是王国，人家其实只是叫自己“伟大的亚历山大”而已。而阿拉伯帝国是由哈里发（Caliph或者Calif）统治，所以应该是哈里发国（Caliphate）。而第三帝国是由以希特勒为元首的纳粹党统治的，希特勒并没有称帝，所以纳粹德国应该是党国。

之所以会这样，是因为在中国，我们认为皇帝比王要高一级，有上下之分。春秋之前，天子为王，是最大的，春秋五霸中齐恒公晋文公都只是侯爵而已，所以叫诸侯，叫“公”只是对去世后的国君的一种尊称而已，不是公爵。后来战国七雄都想当老大，于是都成了王。再后来秦王灭六国，再称王感觉没啥进展，于是称自己皇帝。明初姚广孝见到燕王朱棣时就问他：“给你一顶白帽子带要不？”“王”带白帽子便为“皇”，这个故事是真是假不知道，但王和皇有上下级关系是明显的。

但是在欧洲却不是这样子。欧洲国家形成有两个模式，一个是古罗马的中央集权，另一个是日耳曼民族的封建制度。

所谓emperor（皇帝），一开始只是军事统帅的意思。在罗马共和时期，为了避免独裁，元老院通常会选出两名执政官，每人配备12个保镖，每个保镖带一把藤条绑着的斧子。如果遇到犯法的人，就会被保镖用藤条抽一顿，然后用斧子把头剁掉。这把用藤条绑着的斧子就叫“法西斯”（fasces）。到了战争时期，为了避免两个执政官扯皮，就会推选出一个成为军事指挥官全权负责，当这个指挥官能获得成功时，会被封为imperiator（拉丁文，英文就是emperor），是成功的指挥官的意思。后来这个抬头先后授予了凯撒（扑克牌的方片K）和屋大维，也就被他们垄断了，成为了至高无上的统治者，罗马人的守护者的意思，也就是我们所翻译的皇帝。而凯撒，也等同于神一样的人，半神，也成为皇帝的代名词，神圣罗马帝国、德意志帝国、奥地利帝国的皇帝便称为凯撒（Kaiser）；俄罗斯沙皇（Tsar）也是凯撒的意思。屋大维，则被封为现人神“奥古斯都”，因此奥古斯都也是皇帝的意思。当奥古斯都和凯撒同时出现时，奥古斯都就是正皇帝，凯撒是副皇帝（罗马四帝共治）。

相对于罗马文明，刚刚入侵的日耳曼人就是野蛮人，国王king，词源同 kin, 原指一个家庭或一个氏族的首领，这就到头了。而在蛮族传统里，首领是没有特权的，打仗你要冲前面，分战利品跟大家分的是一样的。因此不论你英女王维多利亚多么厉害，对于约克公爵等贵族而言，你就只是我们的王而已。你要真想当至高无上的统治者，去印度当去。因此维多利亚的头衔是“大不列颠及爱尔兰联合王国女王及印度皇帝”。这有点像当年满清刚入关的时候。对于汉人而言，顺治帝是皇帝，拥有至高无上的权力。但是在八旗贵族内部，他们仍然实行的是“八王议政”，由极少数的几个皇亲贵胄共同协议一些军国大事，甚至包括推举皇位（汗位）的继承人，皇帝是没有独断专行的权利的，仅仅只是一个汗王而已。
Royal这个词的正确翻译是“王国的”，而不是“皇家的”，因此英国的The Royal Air Force不应该翻译为“皇家空军”，而应该是“王家空军”。英国的各种royal都是王家的，不是皇家的。另外美国总统住的White House，学过英语的人都知道应该翻译为“白房子”，又不是White Palace，可我们却翻译为“白宫”，因为宫是皇家王室住的地方。人家美国总统又不是皇帝。但是英国的白金汉宫（Buckingham Palace）和法国的凡尔赛宫（Chateau de Versailles）倒是货正价实的“宫”。还有天主教的Pope，现在翻译为“教宗”了，以前中世纪如日中天的时候被我们翻译为“教皇”，我们其实只是想表达他权势很大，跟“皇”似的，但其实人家从来没有称自己为“皇”。

回到突厥，此时此地的突厥已经伊斯兰化，因此称自己首领为苏丹，类似于东周列国的诸侯，而哈里发则类似于东周的天子，因此建立的国家叫苏丹国（sultanate）。
此时阿拉伯帝国已经分裂为三个国家——逊尼派的科尔多瓦哈里发国（Caliphate of Córdoba，白衣大食，图21左部）和阿拔斯哈里发国（Abbasid Caliphate，阿拔斯王朝，黑衣大食，图21右部）以及什叶派的法蒂玛哈里发国（Fatimid Caliphate，法蒂玛王朝，绿衣大食，图21中部），而塞尔柱苏丹后来几乎已经完全控制了阿拔斯哈里发国的哈里发，他的苏丹国已经远远强大于阿拔斯哈里发国，而被称为塞尔柱帝国。
 
图22 塞尔柱帝国

塞尔柱突厥的崛起，引发了西方一件重大事件。公元1070年塞尔柱帝国攻占阿勒颇，势力扩张到耶路撒冷和大马士革。以前阿拉伯帝国的宗教政策很是宽松的，无论是天主教徒还是东正教徒还是犹太教徒，都允许他们到耶路撒冷来朝圣。所以尽管圣城在伊斯兰教徒的控制之下，哪怕多交税多给过路费都不要紧，只要不妨碍他们释放他们的宗教情感需求就行。但是突厥穆斯林不一样了，塞尔柱帝国不再允许基督教徒来耶路撒冷朝圣，这下就掐住了西欧天主教徒的命门了。无法去朝圣，对一个虔诚的教徒而言是一件多么痛苦的煎熬。为了解决这个需求，1095年教皇乌尔班二世在克莱蒙费朗（法国中南部城市）号召第一次十字军东征，以夺回被异教徒占领了457年的圣城（公元638年耶路撒冷被阿拉伯帝国占领），开始了基督教和伊斯兰教几个世纪的流血仇恨。

塞尔柱帝国也是个封建国家，封了很多小国，后来也是中央不行了，各个小国开始独立，互相攻伐，跟东周天子不行了，春秋战国诸侯混战一个样。不一样的是，这里流动性很强，有很多外患，例如东边的花剌子模，例如西边的天主教十字军，例如南边的萨拉丁的埃及阿尤布王朝，例如北边有拜占庭。这些小国家里面，活得最久的是罗姆苏丹国（Sultanate of Rome），位于小亚细亚，由于东方人称拜占庭统治下的小亚细亚为罗姆，其实就是罗马，因此叫罗姆苏丹国。最后罗姆苏丹国被第三次西征的蒙古灭了。

罗姆苏丹国也是个封建国家，下面也有很多小国，其中有一个叫奥斯曼的，在苏丹国的西边拥有一块小领地。趁着罗姆苏丹国被蒙古欺负的时候，奥斯曼也跟其他小国一样开始独立，而随着蒙古结束第三次西征撤回蒙古草原，奥斯曼开始扩张，后来吞并了罗姆苏丹国的大部分领地。强大之后，他们以奥斯曼为自己国家的名字，这就是奥斯曼突厥帝国。对！就是奥斯曼土耳其帝国。突厥，就是Turkey，就是土耳其。
 
图23 奥斯曼土耳其帝国

而这个帝国是货真价实的“帝”国。前面说了，凯撒开始独裁，屋大维于公元前27年开始称帝，成为“罗马人的皇帝”，后来东西罗马分裂（公元395年），因此出现东西两个皇帝。
西皇帝于公元800年被教宗加冕给罗马帝国的继任者，基督教会的保护人，伟大的查理曼大帝（Charlemagne或Charles the Great，扑克牌的红桃K，其实人家只是叫查理，后面的“曼”-magne是伟大的意思。）。因此查理曼大帝的法兰克帝国成了新的罗马帝国，法兰克人成了新的罗马人。后来法兰克帝国分裂为东法兰克王国（现在的德国），中法兰克王国（现在的意大利、瑞士、卢森堡、比利时、荷兰）和西法兰克王国（现在的法国）三部分，中法兰克又被东西法兰克瓜分。随后东法兰克的国王奥托一世被教宗加冕为“罗马人的皇帝”，成为罗马帝国的继任者，基督教会的保护人，因此东法兰克后来改名为神圣罗马帝国（公元962年）。

西法兰克倒是一直以法兰西王国自称，直到后来拿破仑崛起，横扫欧洲，自称自己是罗马教廷的守护者，因此被加冕为“法兰西人的皇帝”，等同于“罗马人的皇帝”，建立法兰西帝国（公元1804年）。并将神圣罗马皇帝弗朗茨二世打败，因此弗朗茨二世取消了神圣罗马帝国的称号，仅称自己为奥地利皇帝，治下是奥地利匈牙利帝国（公元1806年）。不过拿破仑一届皇帝没当完就被打败了。后来他侄子借着他的名气复辟了法兰西帝国（公元1852年），称拿破仑三世，也是一届皇帝没当完就打败下台了。
打败他的，就是原神圣罗马帝国内的一个封国普鲁士。普鲁士国王威廉一世在法国的凡尔赛宫加冕，成为“罗马人的皇帝”，罗马帝国的继任者，基督教会的保护人，Kaiser，建立德意志第二帝国（公元1871年，第一是神圣罗马帝国，第三是1933年由希特勒建立的纳粹德国）。

这些皇帝的法统都是来自西罗马皇帝。
东罗马皇帝就一直好好的，也就是拜占庭皇帝，直到奥斯曼苏丹穆罕默德二世攻占拜占庭首都君士坦丁堡，改为伊斯坦布尔，东罗马灭亡。穆罕默德二世宣称自己继承东罗马衣钵，正式成为“罗马人的皇帝”，因此国家即为奥斯曼土耳其帝国（公元1453年）。
另外，当年拜占庭为了拉拢俄罗斯，将一个公主嫁给了莫斯科大公，换取俄罗斯皈依基督东正教，因此后来的莫斯科大公都是东罗马皇帝的外孙，是有资格继承皇位的。再加上末代拜占庭皇帝君士坦丁十一世的侄女——索菲亚•帕列奥罗格公主，最后选择嫁给东正教的莫斯科大公伊凡三世，而不是天主教的西欧君主，因此莫斯科公国便以拜占庭帝国的继承人自居，成为俄罗斯帝国，即沙皇俄国，莫斯科大公继承凯撒的头衔，加冕为沙皇（Tsar）（公元1547年），并将索菲亚带来的东罗马象征双头鹰奉为国徽（现在普京仍在使用），称莫斯科为第三罗马（第二罗马是君士坦丁堡）。见图24。



图24 欧洲皇帝图
