# 女真金国

话说北宋跟契丹签了澶渊之盟，享受了一个多世纪的和平时光。真正受益的，是市井百姓。但是对于统治阶级，他们却有不同的感受。首先，不平等条约就是不平等条约，想洗刷耻辱的冲动是会一直存在的。其次，燕云十六州把控在辽国手上，就像自家大门钥匙在隔壁程咬金手上握着，谁知道他什么时候会冲进来抢一把。更何况，夺回燕云十六州，一直是中原仁人志士的梦想，若能成功，必然名垂千古。

终于机会来了，契丹被自己的小弟胖揍了一顿。就像柔然有突厥这样的小弟一样，作为一个强大契丹，底下也有很多小弟。而胖揍了大哥的这个小弟，就是女真。
女真，源自3000多年前的肃慎，汉至晋时期称挹娄（yì lóu），南北朝时期称勿吉，隋至唐时期称靺鞨（mò hé），辽朝时期称“女真”，宋朝人说女真族“本名朱里真，番语。讹为女真”。《金史•世纪》记载：“金之先，出靺鞨氏。靺鞨本号勿吉。勿吉古肃慎地也。元魏时，勿吉有七部；隋称靺鞨；唐初，有黑水靺鞨，粟末靺鞨。”

女真不是游牧民族，而是渔猎民族，一直生活在现在的东北地区。唐朝的时候，粟末靺鞨首领大祚荣在现在的东北建立渤海国（参见图25），后来被契丹灭了。女真人人口不多，但是性格倔犟，桀骜不驯，难以顺服，战斗力极强。好不容易平定渤海国的耶律阿保机给的评价是：“女真不满万，满万不可战。”
为了方便统治女真族，契丹把一些强宗大姓南迁至辽东半岛，编入契丹国籍，叫熟女真。这些人就跟契丹融合得比较好，比较好管理。而那些不够强大的部落，就留在北方，叫生女真。这些人就跟契丹走得比较远，难以驯服，不好管理。而不论是生女真还是熟女真，对于契丹人而言都是二等公民，肯定得不到什么公正的待遇，压迫奴役剥削，肯定少不了。而生女真受到的不公正待遇肯定更为不公正。不过还好生女真不够强大，多欺负一下应该不要紧吧。

可是再不强大的群体里也有最强大的一个，而且今天不强大，不等于明天也强大不起来。同样道理，你今天强大，不等于明天还能继续强大。契丹就越来越不行了。此消彼涨，在这帮不强大的生女真里也站起了一个强大的完颜阿骨打。新仇旧恨，咱们算算吧。公元1114年，完颜阿骨打正式起兵反辽，并且节节胜利，公元1115年正月，完颜阿骨打即皇帝位，建立国家，国号大金。于是由东北向西南，开始了灭辽之战。公元1116年，金国攻下辽国东京辽阳府（今辽宁省辽阳市），公元1120年，金国攻下辽国上京临潢府（辽国主要首都，今内蒙古赤峰市巴林左旗林东镇南郊），此时金国已经攻占辽国过半疆土。

听说契丹被小弟揍了，北宋很开心，觉得机会来了，于是宋徽宗派使臣渡海赴金与之结盟，相约夹攻辽国。金国也很开心，多个帮手报仇。双方一拍即合。辽国设置五京，分上南东西中，其中上京临潢府和东京辽阳府已经被金国拿下。于是双方说好，金国打中京大定府（今内蒙古赤峰市宁城县天义镇原铁营子镇下辖区域），宋国打南京析津府（今北京，就是当时的幽州），打下来之后兵合一处，一起打西京大同府（今山西大同，当时的云州），灭亡辽国之后，原先属于汉地的燕云十六州和以南的土地归宋国，以北归金国。双方互换国书，立下盟书，是为“海上之盟”。

这次“海上之盟”，是宋国对辽国的背信弃义，单方面撕毁条约。再不平等的条约，也是双方协议签署的。有意见，可以以国家实力为后盾再行协议修改。盗亦有道，如此不讲信用，无视规则，没有一点契约精神，连强盗都不如。为了一个所谓崇高，亵渎另一个崇高。
而从地缘政治的角度来看，虽然燕云十六州在辽手上，但是此时辽已经强弩之末，其实没啥进攻性了，而且跟宋已经和平相处了达百年之久，很安全。反而是新兴的女真更具扩张性，辽国实际上已成为宋金之间的缓冲带。把安全的辽灭了，换个更强悍的金，是个明智之举吗？这一点，甚至高丽国王也看得清楚。他给宋徽宗带话：“闻朝廷将用兵伐辽，辽为兄弟之国，存之足为边捍；金为虎狼之国，不可交也！”（《宋史》第二百四十六卷）
而且当时辽国也担心宋金夹攻，已经遣使对宋奉表称臣。此时完全可以让辽把燕云十六州割还回来，再帮助辽抵御金的入侵。但是宋徽宗就是看不惯辽国，一定要联金灭辽。

那就履行合约吧。公元1121年，宋金双方同时出兵，金国南征中京，宋国北伐南京。可惜人算不如天算。剧本写得好好的，人家辽国不按你剧本来演。金国攻打中京时，宋国在攻打南京；金国打下中京时，宋国在攻打南京；金国抵达西京时，宋国在攻打南京；金国打下西京时，宋国在攻打南京；金国抵达南京时，宋国还在攻打南京。于是宋国只能眼睁睁地看着金国攻陷南京（公元1124年）。
 
图33 金灭辽过程

为什么北宋打不下辽国南京？

其实宋朝战斗力不行，这是公认的。当年“借酒释兵权”虽然成功防止了军头造反，解决了内忧，但造成了战斗力低下就搞不定外患了。再经过百年和平的腐蚀就更加懈怠了。另外燕云十六州的老百姓经过一百多年的休养生息及辽的汉化统治，早已和当地人融为一体。他们自我认同为辽人，而不是宋人，并不像当年柴荣北伐时一样思念故国仰望朝廷。面对着“王师”挑起的战争他们不会箪食壶浆去欢迎，而是对战火破坏自己家园感到仇视和憎恶。

所以北宋两次北伐都以失败告终，只能眼睁睁得看着金国拿下南京，灭掉契丹。

说一下契丹的余波。辽末代皇帝天祚帝失去了大部分土地，于是退出漠外，公元1125年，被金人俘获。辽灭亡。贵族耶律大石在西北召集残部，控制了蒙古高原和新疆东部一带。公元1130年，由于受到金国所迫，耶律大石决定放弃蒙古高原，率部西征。公元1132年，耶律大石在叶迷立（今新疆额敏）称帝，史称西辽（西方称为黑契丹或哈剌契丹），曾一度扩张到中亚，成为中亚强国。后为成吉思汗的蒙古所灭。
 
图34 西辽
公元1212年，辽朝宗室耶律留哥在隆安（今吉林省农安县）、韩州（吉林省梨树县）一带起军反抗金朝。公元1213年，耶律留哥称王，国号辽，史称东辽。公元1216年初，耶律留哥之弟耶律厮不叛变，在澄州（今辽宁海城）称帝，史称后辽。后因贵族自相残杀，后辽于公元1220年灭亡。而东辽归附蒙古帝国，成为藩属。公元1270年，元世祖忽必烈撤藩，东辽正式灭亡。

回到宋国。攻下南京后，宋国说：“咱俩合力把辽国灭了！咱俩成功了！按照之前合约说好的，瓜分咱俩的胜利果实吧。”你让金国怎么想？“辽国五京我先拿下了两京。签完合约后，说好一起拿下三京的，结果你一京都没拿下，最后南京还得我来。辽国几乎是我一手拿下的，你好意思说分成果？”宋国说：“不分就不分，算了，我就当来燕国旅游一趟算了。回家！”
宋国是白来一趟吗？不是，宋国不是白来一趟，宋国将自己低得掉渣的战斗力完全展示给金国看。相当于小肥羊跑到饿狼面前秀了自己一身肥肉，你还想全身而退吗？

公元1125年，金国发动灭宋之战，分兵两路从山西、河北南下，最后会师北宋首都开封。不过这次在宋将李纲死守下，金国不得不和南宋议和。公元1126年，金太宗再次兵分二路进攻北宋，这次成功攻破开封，俘虏宋徽宗、宋钦宗等宋朝皇室北归，史称靖康之祸，北宋灭亡。

宋康王赵构因机运逃过一劫，就跑到宋朝南京应天府（今河南商丘）称帝重建宋朝，是为宋高宗，史称南宋。后迫于金国压力，迁都临安（今浙江杭州）。以长江为防线，在江北淮南一带与金国拉锯。
 
图35 金国疆域图（公元1142年）

宋辽金，有史学家建议叫为中国的第二个南北朝。当时的文书往来就把宋国称为南朝，管辽或金称为北朝。

随着中原国土的再次沦丧，又一批中原人士大举南迁，带来了第二次南部大开发，而此时江南已成为中国经济最发达地区。当时首都开封在河南，当时的河南话才是官方普通话。有一支操着当时河南话的移民就一直走到了广东，为了争夺生存空间跟当年操着河洛语的广府人（说粤语）和潮州人（说闽南语）起了很大冲突。广府人和潮州人从五胡乱华开始就在这里定居生活（其实也是侵占了之前的原住民），自认为是主人，那这些新来的就是客家人，当年的河南话就变成了现在的客家话。

南宋已经偏安江南，中原故土沦丧殆尽。收复中原，就像当年的东晋一样，成为很多有志之士的梦想。例如岳飞就一直想要“直捣黄龙，迎回二圣”（黄龙府，今吉林省长春市农安县县城内，为辽金两代军事重镇和政治经济中心，宋徽宗宋钦宗曾关押在此）。陆游也有诗写到：“王师北定中原日，家祭无忘告乃翁。”

在殷切的期望中，一个似曾相识的场景重现了，一个熟悉的机会降临了。金国的一个小弟，开始胖揍老大金国。这个小弟，就是蒙古。
