# 满清

话说蒙古当年灭金，女真在东北还有几家穷亲戚，分为建州、海西、野人（东海）三大部（见图51）。明朝将大元赶回大漠，他们也就归降了明朝。毕竟没跟着完颜本家来中原沐浴中华文化，因此保留了好多蛮族习惯，因此在明朝看来就是野蛮人，二等公民，没少受欺负。其中建州女真离明朝最近，因此先后设置了三个地方军事行政机构，包括建州卫（建于正统三年1438年）、建州左卫（建于正统五年1440年）和建州右卫（建于正统七年1442年）。

万历十一年（1583年），出身建州左卫指挥使世家的金子•野猪（金子满语发音为爱新觉罗，野猪满语发音为努尔哈赤，有一说法是“野猪皮”，有一说法是“像野猪一样”）以先人所留下的“十三副遗甲”起兵，开始了他之后建国称汗的道路。

公元1588年，努尔哈赤征服建州。

公元1599年，努尔哈赤分化削弱海西女真。

公元1613年，吞并野人女真，几乎一统女真。

公元1616年，努尔哈赤在赫图阿拉称汗，国号“大金”，史称后金。

公元1618年，努尔哈赤在盛京（今沈阳）发表“七大恨”誓师，正式与明朝开战。

公元1619年3月，努尔哈赤在萨尔浒以2万兵力打败明朝十万大军。

公元1619年8月，消灭海西女真最后一部——叶赫部。
 
图51 后金

叶赫部，又称叶赫那拉，意思是河边的太阳。传说，在叶赫部首领布扬古在被努尔哈赤处死前曾经对天起誓：“我叶赫那拉就算只剩下一个女人，也要灭掉建州女真。”虽然说爱新觉罗和叶赫那拉结下不共戴天之仇，但比起汉人来，毕竟大家还都是女真人，肯定更亲一点。尽管有过战争，但还是不妨碍联姻的。努尔哈赤的皇后就是叶赫那拉氏，而大家最熟悉的嫁给爱新觉罗的叶赫那拉氏，就是三次垂帘听政、在宫中执权48年之久的慈禧太后。大清算是毁在她手里吗？

努尔哈赤纵横辽东，始终未能突破袁崇焕的关宁锦防线，就是山海关-宁远-锦州防线，还把性命搭了进去。于是通过“八王共治”选出了八皇子爱新觉罗•皇太极继位，这就是后来的清太宗。（1627年）
清太宗说：“你可知皇太极，不是我真名~”
你想想，他比较有名的几个兄弟，老大废太子爱新觉罗•褚英，老二爱新觉罗•代善，堂兄弟爱新觉罗•阿敏，老五爱新觉罗•莽古尔泰，老十二爱新觉罗•阿济格，老十四爱新觉罗•多尔衮，老十五爱新觉罗•多铎，这些名字都不是汉名，单单清太宗叫了个不正常又汉味十足的名字。清太宗1592年出生，他爹正忙着打海西女真，连国都没有，只是一个大部落，根本谈不上什么汉化。
那他真名是什么呢？关于皇太极的本名有几种说法，一说是叫阿巴海（由俄罗斯汉学家G.V.戈尔斯基提出），一说是叫黑还勃烈（朝鲜《李朝实录•仁宗实录》第十四卷：“奴酋死后，第四子黑还勃烈承袭。”因为皇太极在四大贝勒里排第四。）。

说本名为“阿巴海”，很可能是把皇太极的第一个年号天聪误解为本名，因为天聪的满语发音是Abkai sure，被音译为“阿巴海”。而黑还勃烈，应该是黑还贝勒，就像代善贝勒，阿敏贝勒，莽古尔泰贝勒一样。四大贝勒嘛。所以“黑还”应该是清太宗的本名，黑还在满语里是獾的意思，多尔衮是熊的意思，阿济格是小的意思，多铎是胎儿的意思。

那为什么要改成“皇太极”呢？

蒙古灭金，使得女真受到很深的蒙古化，而大元又学习了很多汉文化，因此后金沿用蒙古制度，用了很多汉音的官名，例如亲王叫济农，夫人叫福晋，将军叫章京，而太子叫台吉（蒙古语为Tayiji）。本来汉文化里只有继承权的皇子才叫太子，但是传到蒙古，把所有的皇子都称为台吉，毕竟大家都有继承权嘛。而为了突显特殊尊荣，会在台吉前面冠以黄（鸿，洪，浑，欢），称为黄台吉（鸿台吉、洪台吉、浑台吉、欢台吉，蒙古语为Khong  Tayiji）。本来也是只用于明确的储君，相当于“皇太子”，后来非太子、长子的蒙古贵族也可拥有此称。俺答汗的长子继承汗位之后，明朝称其为“顺义王黄台吉”，他请求改称为“顺义王乞庆哈”（《北元史》第七章），这才是他的本名。在清初汉语典籍中, 皇太极的名字就是被记载为“黄台鸡”或“黄台吉”，后来到了清高宗乾隆帝时期，才钦定为“皇太极”。而除了有可能是突显殊荣外，对于清太宗而言，还有一种可能，就是黄台吉可能仅仅是“黑还台吉”而已，就像“黑还勃烈”一样，因为“黑还”也可以音译为“黄”。

由于之前蒙古化很严重，所以女真对蒙古有种天生的亲近感，因此跟蒙古一直走得很近。满清对蒙古的基本国策，是“北不断亲”。整个中国史，就属满清的和亲政策最为成功，跟蒙古是亲如一家。努尔哈赤通过娶老婆娶儿媳嫁闺女的方式，不动一枪一刀，便将察哈尔的科尔沁部、内喀尔喀部等收编入八旗军。在皇太极的9位后妃中，有6位是蒙古后妃，而且所立五宫后妃全是蒙古女子，其中包括后来大名鼎鼎的孝庄皇太后。努尔哈赤时，同漠南蒙古联姻共39次，其中同科尔沁部联姻就占了11次；皇太极时，同漠南蒙古联姻共41次，其中同科尔沁部联姻就占了18次。于是蒙古成了后金的强大后盾。

皇太极上位之后，第一步肯定是要报杀父之仇，于是继续在关宁锦防线跟袁崇焕硬干，但还是占不到便宜。他爹就是这么被怼死的，他可不想走他爹的老路。那就学会曲线救国吧。先不直接南下，先西向蒙古，征服整个察哈尔部（1627年），再从蒙古南下北京（1630年）。虽然袁崇焕及时回师，拱卫京城，但不敢直接跟后金骑兵野战，只能依靠北京城打守城战才有胜算。皇太极也不傻，看你北京城守得跟铁桶似的，我才不攻城呢，要就出来打野战。结果袁崇焕只能眼睁睁地看着皇太极在京师附近烧杀抢掠而无所作为，等他抢够了，粮草吃完了，自然就回东北了。这就是“己巳之变”。

虽然没有更好的选择，可这个最好的选择也不是什么好选择。北京城外死了多少平民百姓？你重兵在手就这样龟缩在北京城内，你窝不窝囊？换了你当皇帝你能咽得下这口气吗？总得找个人对这事件负责吧！直接负责人当然是皇太极，但你不能拿他怎么滴。那是谁在负责不让皇太极杀进来的？当然是蓟辽督师袁崇焕啦。你不是说五年之内要把后金灭了的吗！怎么人家差点跑进来把我给灭了！再加上一些其他的事情，最后袁崇焕被定为通敌叛国，凌迟处死。
皇太极也明白了，一口吞不下个胖子，明朝不是那么容易灭的，那就先做些别的准备，学会等待机会吧。1635年，皇太极将族名女真改为满洲，从此他们便为满人。1636年，在盛京（今沈阳）称帝，改国号大清，改元崇德。这些改变，都是为了向汉人表明一个态度，我们跟当年那个一登场就欺负你们南宋汉人、一直都在欺负你们南宋汉人、快死了还不忘欺负你们南宋汉人的完颜女真金国不一样，我们是全新的满洲大清。我们是要入主中原的，要替代如炼狱般的明朝，解救你们，成为你们的统治者的。因为明朝是火运，按照你们五行学说，水克火，所以我改为满洲，改为大清，都带水的。

这其实就是在忽悠我们汉人，因为在满语里面，“清”和“金”是谐音。对汉人而言，“清”和“金”不同，但对满人而已，你翻译为“清”或“金”是一回事。天聪年间立的盛京（今沈阳）抚近门匾额，上面汉文写的是“大金”，而满文写的就是“大清”。那时候国号还没改呢。
除了做做文字功夫，搞点心理战术，皇太极还是做了些实际工作的。例如1637年，把明朝的藩属朝鲜给灭了，解决了后顾之后。这下可以全力以赴南征灭明了。

不过皇太极没成功灭明，就归西了。他儿子福临继位（顺治帝），他弟弟多尔衮掌舵（摄政王），继续灭明事业。不过也没成功，因为明被闯王李自成灭了。
其实明朝也算是倒霉。往年也有农民起义，而这次闯王李自成也几乎已经被镇压了，没想到死灰复燃。往年也一直有边患，不是蒙古就是后金，但是也一直没有失控。拆东墙补西墙，日子还是能将就过的。可是如果同时后院起火又前线告急，明朝就招架不住了。
李闯王进京，崇祯皇帝上吊，吴三桂降清，多尔衮入关（1644年）。

本来满清入关的理由，是帮助明朝剿匪的。进了北京城，顺治帝就跑到崇祯的墓去哭坟，“哥哥啊！弟弟来晚啦~弟弟对不起你啊！弟弟应该早点到的啊！哥哥放心，你的仇我一定替你报，你的家我一定替你看好，你就安心地去吧~”你既然是来剿匪的，那剿完匪你是不是就该回老家了？此时朱元璋的子孙已经在南京建立了政府，领导班子已经正常工作，中华大地不是没主，你别惦着，不用你操心，有人打理。你安心回去吧。

但是请佛容易送佛难，你当人家真的是来剿匪的？当年的“七大恨”不是白写的。所以剿完匪，明清就继续开打，最后南明节节败退。1662年，最后一个皇帝永历帝被吴三桂用弓弦绞死在云南，南明灭亡。中华大地再次落入鞑虏之手。

那肯定有人不愿意啊，于是到处都有反清势力，明的有台湾的郑成功，暗的有天地会的陈近南，尤其在华南地区最为严重，到处都有“反清复明”的呼声。因此云南的吴三桂被封为平西王，广东的尚可喜被封为平南王，福建的耿仲明被封为靖南王，镇守南方，被称为“三藩”。
三藩手握重兵，还顶个汉奸的头衔，都不忠于大明，岂能忠于大清？于是老戏又要重演了，那就是削藩。

多尔衮死后，顺治帝退位，年幼的爱新觉罗•玄烨登基，这就是康熙帝。他爷爷的历史任务是准备坐江山，他爹的历史任务是坐上江山，他的历史任务，就是坐稳江山。所以在鹿鼎公韦小宝的帮助下（参见金庸先生的武侠小说《鹿鼎记》），南削三藩，东平台湾，北却俄罗斯，西征准噶尔，算是顺利完成历史使命，为大清坐稳了江山。
 
图52 清朝疆域

当年努尔哈赤建立八旗，即是军事组织，也是生产组织。后来大清征服蒙汉，于是依照满八旗，设立了蒙八旗和汉八旗。但凡在旗的，都是旗人。

汉军旗，由被征服后或者被俘虏后归附的明朝国民组成。比如一个蒙古人，在明国朝廷里任职，作战投降归附清国，那么他就归属于汉军旗，而不是蒙军旗。汉军旗下，比较广为人知的，就有范文程，尚可喜，耿仲明和曹雪芹的先祖曹振彦。甚至包括抗清英雄袁崇焕的后人，也是旗人。《清史稿》传记二百零四有记载，袁崇焕七世孙袁世福，满名富明阿，属于汉军正白旗，官拜宁古塔副都统，在江北大营和太平军作战。《清朝各地将军都统大臣等年表》和《满族大辞典》都有记载，袁崇焕九世孙袁庆祺，袁世福之孙，官拜西安副都统，属于汉军正白旗。
蒙军旗，则以被征服归附的蒙古人组成。

满军旗，则成分复杂，主干为最初起兵造反的女真人，包括当时就追随女真人的蒙古人。还有日后归附八旗的回人，高丽人，锡伯人等等各族类。后来无法归入汉军旗和蒙军旗的，那就都算在满军旗下。例如后来清俄战争，有俄罗斯战俘愿意归化清国，就被纳入满军镶黄旗，驻守居住在北京。

一开始皇太极时期说满人，指的是满洲女真人，但后来统一中国后，满人就等于旗人了，也就是包括汉八旗的人。不论你出身于那个族类，只要皇帝觉得你忠诚可靠，把你纳入这个制度，那么你就是旗人，也就是满人。但是你要是犯事了，也可能被开除出旗籍。

满清讲究“满汉不通婚”，说的是旗人和汉人不能通婚。那要是皇上看上了某个汉人女子怎么办？好办！先将该女子抬入旗，成为汉八旗的一员，就成了旗人了，就可以结婚了。
东北龙兴之地，只许满人居住，不准内地汉人移民。因此到了清末放开，才有山东人闯关东一说。蒙古那边，虽然不修长城，然而有柳条边，用柳树隔开蒙汉。因此到了清末放开，才有山西人走西口一说。

北京分内外城，内城是满人居住，外城住汉人，即使位居大学士、各部院尚书，也只能住宣武区。各地方满人驻军区，也分满城、汉城，不相交往。
官员也是满汉两班。汉人当然比满人低一等，同样是都御史，满员为从一品，而汉员则为正二品。

清朝实行这种民族大隔离政策，也实属无奈，因为满人实在太少了。作为一个异族，征服统治了一个多自己二十倍人口的汉人，能不担心吗？看人家北魏拓跋鲜卑，积极汉化，结果现在鲜卑人在哪都找不到了，被消化得一点不剩。因此满清努力保留很多自己的文化传统，例如旗袍，例如马褂，例如辫子。

虽然不汉化是清人的立国之基，但是不汉化也不行啊。这么多汉人，不按他们的方式统治管理他们，会爆发的，就像蒙古元朝一样。为什么东北不让汉人去，为了防止哪天中原待不下去了，像元朝一样被赶跑了，还能有个去处。

不过能不被赶跑还是别被赶跑了，因此从顺治开始，就很热衷学习汉文化，顺治就经常拿自己的字跟崇祯相比，《山志》有记载，僧弘觉向顺治索字，顺治说：“朕字何足尚，崇祯帝乃佳耳。”而康熙编《康熙字典》，乾隆编《四库全书》，都是在学习接纳汉文化。不过这些都是为了方便统治需要。虽然嘴上不承认心里不愿意，但是渐渐地也抵御不了华夏文化的熏陶。比如近现代著名的大画家溥儒溥心畬（yú），原名爱新觉罗•溥儒（与末代皇帝爱新觉罗•溥仪同辈），为清恭亲王之孙，别号西山逸士。他的书画造诣与国画大师 张大千齐名，号称“南张北溥”。又与山水画家吴湖帆并称“南吴北溥”。从他的书画特点来看，继承大宋遗风的痕迹无人能出其右，从骨子里来讲，他完全成了一个汉族士人。

近代以后在与西方交往中，满清还曾经以“中华大清国”的名义来签订条约，简称也叫中国。此后大清国和中国两词混用，逐步使用中国这一称呼替代了大清国。

英国（England）人说的英国话是English，法国（France）人说的法语是Franch，但中国（China）人说的中国话却不是Chinese。Chinese是中文，是写的。说的，不是Chinese。那说的是啥？是Cantonese和Mandarin，就是粤语和普通话。

在英语语法里面，[b][p]，[d][t]，[g][k]是同音的，[p][t][k]叫清塞音，[b][d][g]叫浊音。如果音节[sp][st][sk]后面带了元音，则发音会变成[sb][sd][sg]，例如spy，stay，sky。印度口音[d][t]不分，因此印度英语会把“What are you going to do?”念成“Wha da you going do do?”

在音译的时候，[b][p]，[d][t]，[g][k]是可以通译的。例如大家熟知的福特汽车（Ford）就没有翻译成“福德”。例如塞万提斯小说堂•吉诃德（Don Quixote）就没有翻译成“当•吉诃特”。再例如中国的功夫（Kongfu）就没有翻译成Gongfu。
当年洋人跟满清做生意，只能待在广州十三行，只能在广州做生意。于是老外来了之后问当地人：“这里是哪里？”当地人回答：“立豆係广东（Guang dong）。”（这里是广东省）老外笑着点点头，明白了，这座城市叫Canton。于是广州城就是Canton，那么广州话就是Cantonese，也就是粤语。后来跟清廷打交道，发现他们说的不是Cantonese。北京官方满人说的话不一样，应该是满语，所以叫Mandarin。中国的鸳鸯，英文就是mandarin duck，满清的鸭子。中国的桔子，英文是mandarin orange，满清的橙子。

另外，Chinese，当年是个侮辱性称呼，说中国人Chinese，日本人Japanese，都是蠕虫的档次，因此用-ese后缀，代表泥土里生长出来的。只是发展演变到今天，侮辱性被弱化了。外国人再说Chinese，Taiwanese时，并没有侮辱的含义。但是香港人英文比较好，他们就坚持：我们不是Hongkongese，我们是Hongkonger。所以香港人是用Hongkonger，就像伦敦人Londoner一样。同样英语不错的新加坡人也不说自己是Singaporese，而是Singaporean，就像加拿大人Canadian，澳大利亚人Australian一样。

