# 民国

英语中，“国家”有三个单词，country，state，nation。这三个词各有偏重。country强调的是这个国家所在的土地，因此country也翻译为“乡土”。state强调的是这个国家所采用的政治制度，组织结构。而nation强调的是生活在这个国家的人民，其实nation一开始是翻译为“民族”的。德国纳粹的全称是Nationalsozialistische Deutsche Arbeiterpartei，缩写为Nazi，英文为“National Socialist Deutsche Workers' Party”正确翻译应该是“民族社会主义德意志工人党”，高举的旗帜就是民族（National）和社会主义（sozialistische）。

其实民族，一开始是一个宗教概念，宗教战争之前无民族。

15世纪的圣女贞德，虽然被人称为“法兰西民族英雄”，那是后来人把她定义的，就像后人同样把她定义作“女权主义英雄”一样。在当时是没有这个概念的，她是作为法兰西国王的子民，为法兰西国王的皇冠而战，或者是为了法兰西国王的瓦卢瓦家族而战，而不是为了法兰西这个国家，这片土地。当时的英法战争，一方是法兰西国王，另一方则是英格兰国王和法国勃艮第公爵。勃艮第公爵的子民为了勃艮第公爵与法兰西国王开战，没有问题，没有心理负担。该有心理负担的只限于勃艮第公爵个人，他本应该是法兰西国王的臣民。

天主教，Catholicism，其实应该翻译为普世大而公教会，因为总部在罗马，因此称作罗马公会，罗马公教。明末耶稣会传教士翻译为“天主”，是取自《史记•封禅书》所载：“八神，一曰天主，祀天齐”，表述“最高莫若天，最尊莫若主”和“天地主宰，主宰神、人、万物”，取意为至高至上的主宰，以示与中国所信奉的神灵相区别。中世纪的时候，教宗的天主教在西欧只手遮天。大家除了给国王交税，还得给教会交税。

1517年，马丁路德在德国提出“九十五条论纲”，倡导摆脱罗马教廷的桎梏约束，创建路德宗，开始宗教改革。1533年英王亨利八世，自上而下进行改革，在英格兰创建官方的圣公会。1536年，加尔文在瑞士完成了《基督教原理》，提出“救赎预定论”，创建加尔文教派，传到法国，称胡格诺派或雨格诺派；传到苏格兰，称长老会；传到英格兰，称公理会，信徒称清教徒，后发展出浸信会和贵格会。这各种会的教义各不相同，甚至互相谴责彼此为异端，但是他们有个共同点，就是都反对罗马公教，被统称为抗罗宗，也就是新教。

以前我是天主教徒，要我交税给罗马公会修教堂我无话可说。现在既然我已经入了新教，反对的就是罗马公会，你还让我再交税给罗马公会修教堂，是不是说不过去了？
1618年5月，在波西米亚的首都布拉格，一群抗罗宗的暴民把三个公教徒官员从21米高的窗口扔了出去，历史上称作“布拉格掷出窗外事件”。这是第二次啦。在1419年的时候，胡斯教徒们（马丁路德之前的早期的宗教改革教派）就干过一次。这起事件引发了一系列的连锁反应，欧洲再次陷入大规模的宗教战争杀戮之中，三十年战争爆发。

勃艮第人？加斯科尼人？奥尔良人？不列吞人？不管你老家是法国哪里的，只要大家都是抗罗宗，一起反抗罗马公教的压迫，一起彰显上帝的真理，那就集成了一个统一的集体概念。反过来，巴黎人，奥尔良人，波尔图人，只要你是罗马公会的信徒，大家就一起镇压邪恶的异端，一起彰显上帝的真理，那又形成了一个集体概念。
这个集体概念，就成了民族nation。
1648年10月，欧洲公教和抗罗宗各国终于在多年残酷的宗教战争后走向了理性，大家坐下来通过和平谈判的方式，签署了一系列条约，统称为“维斯特伐利亚和约”（Peace of Westphalia）。这个条约重新建立西方世界的体系。随着19世纪中期到20世纪中期，西方文明全球扩张，这个体系也就拓展成为了全球的政治体系。
维斯塔伐利亚和约定明，公教和抗罗宗都是合法的基督教，国与国之间不再以“异端”“敌基督”的名义互相攻伐。不论什么语言民俗传统，一个国家，一个教会，一个民族。这就是政治学上，民族国家的起源。

根据这个条约，尼德兰南部公教地区形成了公教民族，称作比利时民族，依旧保留在西班牙王冠之下，尼德兰北部抗罗宗地区形成了抗罗宗民族，称作荷兰民族，成立了“尼德兰七国联邦共和国”Republic of the Seven United Netherlands。在这七个抗罗宗国家里，荷兰伯爵国County of Holland最具有实力，也最为活跃。中国人当年遇到了荷兰人，就把那个联邦共和国称作荷兰（参见上一章老外把广州市当作广东省）。由此演变成传统，在中文里，一般就用“荷兰”称呼尼德兰联邦。
 
图 荷兰和比利时

在这个理论下，原先居住在低地地区的一对双胞胎，哥哥信了罗马公教，便搬去南部地区居住，成为比利时民族的一员；弟弟信了新教，就留在北部地区居住，成为荷兰民族的一员。
再例如，一个犹太人放弃了犹太教，成为路德宗教徒，他就成为了普鲁士民族的一员，享有各种同等的权力。比如卡尔•马克思的父亲，恩里克•马克思，他放弃了犹太教，皈依基督教路德宗之后，他就成为了普鲁士民族的一员，而且是一个热忱的爱国主义者，一个在当地有着体面地位的律师。当时政教合一的法律规定，犹太人是异教徒，是不能出任公职或担任律师这些主流职务的。但是不仅恩里克•马克思认为自己是普鲁士民族的一员，当时的普鲁士社会也认同他是社会主流的一员，而不再把他看成是一个犹太人。

例如1948年以色列国建立，流浪世界各地的犹太人终于可以选择回到自己故乡，但是怎么判断一个人是不是犹太人？近两千年的流浪史，流浪非洲的黑种犹太人，流浪远东的黄种犹太人，流浪欧洲的白种犹太人，你凭什么判断他们是同一个民族？宗教！只要你信仰犹太教，熟记犹太教规，遵循犹太教义，依照犹太教律生活，你就是犹太人，你就可以移民以色列，你就可以回家。
 
图 各种肤色的犹太人

随着民族主义思想的觉醒，拿破仑统领着法兰西民族（胡格诺派教徒大多远走他乡，例如美国），动则数以十万计的大军四下征伐，不论是德意志还是意大利，各诸侯国根本无力抵抗人海汹涌的法兰西大军。西方世界的战争就这样进入了“全民战争”（Total War）的时代。
不甘心被奴役的欧洲理性人士开始了“民族国家”（nation state）的呐喊，民族国家的概念出现了。不论普鲁士人，巴伐利亚人，黑森人，大家都是德意志民族的，联合起来对抗拿破仑的大军。

1813年，标志着法兰西帝国崩溃的莱比锡会战，因而又被称作民族会战（the Battle of the Nations），这是不愿意被奴役的德意志民族崛起，为捍卫自己的自由而作的战斗，不再是为王位而战，不再是为宗教而战。他们通过结成一个民族，对抗人数庞大的法兰西民族大军的征服，为自己民族的自由而战。

1815年，惠灵顿公爵在滑铁卢粉碎了拿破仑皇帝重建罗马帝国的迷思之后，获得自由的欧洲各地理性人士先后走上了民族主义的道路。民族主义政治学理论在欧洲大陆开始蔓延，原来的“一个国家，一个民族”的理解，走向了“同一个民族，组成一个国家”的认知。于是渐渐地nation也可以翻译为“国家”了。

1848年，又爆发革命了。这一次革命，是一波席卷欧洲各国的革命浪潮，最初的起源点是在意大利，这股革命浪潮的两个主题思想是，民族主义和自由主义，因此被称为“民族之春”（Spring of Nations）。虽然这场革命浪潮最终在各地都失败了，维护君权的神圣同盟勉强维持住了局面，但是“一个民族，一个国家”的政治理念在德意志各国和意大利各国已经开始要爆发了。
1848年，萨丁王国开始崛起了，“一个民族，一个国家”的呐喊在意大利半岛各地响起。已经无力维持局面的奥地利只能眼看着萨丁王国逐步征服各国。1861年，在东罗马帝国退出亚平宁半岛之后，意大利终于又一次出现了一个统一的国家，意大利王国成立。

1862年，普鲁士王国以“一个民族，一个国家”，“团结就是力量”为号召，开始吞并德意志各国，崛起成为欧洲大陆的一个新兴强国。

在普鲁士崛起的这个吞并过程中，出现了一个问题。我们之前说过，维斯特伐利亚和平条约，是现代民族国家在政治学上的起源。但是维斯特伐利亚和平条约的具体规定是：一个国家，一个教会，一个民族。可是抗罗宗普鲁士在这个“将同一民族的国家联合起来”的吞并过程中，却吞并了南部一批公教国家，例如巴伐利亚王国。

如此一来，按宗教来定义民族的标准就不成立了。为了合法化这个新出现的德意志帝国，学者们对民族进行了再定义，这就出现了“种族民族”Ethnic Nation。种族民族理论和宗教民族理论的关键区别是在于共同的祖先，血缘的纽带。这个时候的民族nation，其实是race，开始变成“人种”概念。那么根据这个理论，卡尔•马克思的父亲哪怕放弃了犹太教，皈依基督教路德宗，他还是会被看成是一个犹太人。纳粹为啥被称作种族主义？纳粹是民族社会主义工人党，而他所谓的“民族”，其实是依据人种作划分。

在19世纪人种理论崛起的时代，高加索人种下又划分出了许多亚种。夹杂着许多神话传说色彩的雅利安人被说成了德意志民族的起源。这个理论会随着历史的发展越走越远，要到二战以后，欧洲基本归向自由主义，全面世俗化，主流才不再谈民族了。那是人种优劣伪科学的时代背景，最初的起源就在于“种族民族”学说的兴起。

根据种族民族理论将德意志各国吞并之后，普鲁士王国崛起成为欧洲新兴的大国，以普鲁士王国为中心结成一个新的帝国，建立起了德意志帝国（1871年）。

新崛起的普鲁士首相俾斯麦喊出了“强权就是正确”的口号might is right，要求重新规划西方世界的政治格局，其中重要的依据就是“一个民族，一个国家”，以民族国家作为建立欧洲新政治格局的依据。普鲁士的口号得到了俄罗斯，意大利和法兰西的响应，“一个民族，一个国家”，建立起新的民族国家政治格局，这成为了欧洲大陆的时髦口号。
对这个口号感觉到压力最大的，就是被称为“西亚病夫”的多民族多宗教的奥斯曼土耳其帝国。在民族国家理论兴起的现实背景下，已经带来一批基督教民族国家的独立，而要奥斯曼土耳其帝国继续维持多民族多宗教的合一已经不再现实了。

1877年，沙皇政府打着“拯救土耳其帝国压迫下的基督徒”和“保护斯拉夫兄弟”的旗号，对土耳其开战，打响第十次俄土战争。最后在西方列强的斡旋下，1878年8月，欧洲各国签订了“柏林条约”，这代表着民族国家政治理论在欧洲正式崛起了。

依据“柏林条约”，巴尔干地区的一批东正教国家获得了独立，或者取得了自治地位。罗马尼亚，黑山和塞尔维亚脱离奥斯曼帝国成为独立国家，保加利亚获得了自治地位，波斯尼亚-黑赛格维那则划入了奥地利帝国管理。这意味着奥斯曼土耳其帝国很快就要分崩离析了。
看着奥斯曼土耳其帝国的分崩离析，同样是多民族多宗教的“东亚病夫”中华大清国是何感受？

维新失败后，维新派流亡海外，学习了当时的“种族主义”思想，提出了“黄帝子孙”的概念，后来加入了炎帝，就变成“炎黄子孙”。现在看来其实还是满邪恶的，充满了种族歧视。1897年，梁启超就撰文写到：“彼夫印度之不昌，限于种也。凡黑色、红色、棕色之种人，其血管中之微生物，与其脑之角度，皆视白人相去悬殊”其实梁启超不知道，印度的统治阶级是正了八经的白种人，雅利安人。康有为更提出，“其棕黑人有性情太恶，或有疾者，医者饮以断嗣之药，以绝其传种。”（《大同书》）
既然倡导种族主义，提“孔孟”就不合用了，所以“黄帝”应运而兴。1899年，康有为在加拿大演讲时，开口就说：“我国皆黄帝子孙”。

不过维新派口中的“黄帝子孙”是包括统治阶级满人的，因为维新派要联合满清一起努力改革建设新中国嘛，当然得是自己人才方便团结嘛，所以最终成了保皇派。但是革命党人则拒绝承认满族是“黄帝子孙”，因为革命党人是要革满清的命，当然不能认同他们是自己人啦。邹容《革命军》写到：“据中国本部，栖息黄河沿岸，而次第蕃殖于四方，自古司东亚文化之木铎者，实惟我皇汉民族焉。”而他在书里认为，满族是“西伯利亚人种”，不是“中国人种”。他在自序里就写到《革命军》成书于“皇汉民族亡国后之二百六十年”（1903年，满清1644年入关）。
紧跟国际潮流的革命党人，当然也希望“一个民族，一个国家”，当然希望炎黄子孙当家作主。那他们不怕中国陷入分裂吗？当然不怕。

孙中山一开始为了革命，提出的口号是“驱除鞑虏，恢复中华”。那把鞑虏驱除到哪里去？当然是回你们东北满洲了！孙中山要恢复的是，是汉十八省的中华。当年的诉求，就是要建立起单一的民族国家。所以武昌起义成功后，中华民国军政府鄂军都督府（俗称湖北军政府）便以铁血十八星旗为旗帜，后成为中华民国的陆军旗。九角，代表九州，十八星，代表汉十八省。
 
图5 铁血十八星旗

汉十八省，也叫内地十八省，关内十八省，包括：江苏、浙江、安徽、江西、湖北、湖南、四川（包括重庆）、福建（包括台湾）、广东（包括海南、香港、九龙、新界）、广西、云南、贵州、直隶（包括北京、天津两市，河北中、南部地区和河南、山东的小部地区）、河南、山东、山西、陕西、甘肃（包括宁夏）。

什么？广西不是壮族自治区吗？那是新中国以后的概念，经营广西多年的桂系军阀李宗仁归顺新中国后，也惊奇地发现：“我以前的地盘现在怎么变成壮族自治区了？”
从清朝到民国，一直是五族概念，也就是汉满蒙回藏，什么锡伯族赫哲族统统算满族，什么哈萨克维吾尔都是回族。没那么多壮族白族水族什么的。不是他们不存在，是他们不受重视。辛亥革命成功后，清帝颁布退位诏书明确写到：“合满、汉、蒙、回、藏五族完全领土，为一大中华民国”。所以北洋政府时期的中华民国国旗是红、黄、蓝、白、黑五色旗，代表汉满蒙回藏，象征五族共和。
 
图 五色旗

既然五族共和了，那就不能局限于汉十八省了，因此陆军旗改为铁血十九星旗。
 
图 铁血十九星旗

随便说一下，1895年，为了准备广州起义，孙中山请陆皓东设计了青天白日旗，后来主要被当作军旗使用，因此又设计了青天白日满地红作为国旗。但是由于该旗是孙中山同盟会一党设计制定的，不能代表全民的意志，因此没被采纳。最后在孙中山的倡导下，青天白日旗仅仅成为了海军旗。青天白日旗不受重视，让孙中山很伤心。于是1914年孙中山组织中华革命党（后来改为国民党）后将青天白日旗作为党旗，一直沿用至今。1920年11月25日，孙中山在广州重组军政府，宣布废除五色旗，正式将青天白日满地红旗定为国民党的中华民国国旗。
     
图 青天白日旗与青天白日满地红旗

对铁血十八星旗提出异议的，是已经经历了闯关东之后的东三省。这时候的东三省已经有很多汉人迁徙过去讨生活了，他们成了东三省的主要人口，当然不希望被祖国抛弃了。那蒙古呢？虽然经历了走西口，但是汉人能抵达的地方也局限在内蒙古，也没占优势。因为闯关东之前满人大都入关了，所以东北没多少人，但是蒙古人一直还生活在蒙古。作为一个整体，蒙古族仍然是蒙古的主体。

蒙古的想法就不一样了。

因为蒙古跟满清关系很好，接受满清统治他们觉得无所谓，都是一家人。但是满清不当皇帝了，你们汉人说话拿事了，我为什么还要继续跟你一起玩呢？
汉人说，依据大清《退位诏书》，中华民国继承“满、汉、蒙、回、藏五族完全领土”，蒙古是其中一部分啊，我们的法理来自这里。而且是“五族共和”，又不是汉人压迫统治蒙古人，为什么不接受呢？

蒙古人说：来来来，我们来讲讲道理。
如果你承认《退位诏书》，也就是接受退位之前大清统治的合法性，那么你们造反就是不合法的。正是因为你们不合法的造反，才导致大清合法统治的动摇，才导致《退位诏书》的出台。因此你们不应该造反，大清也不应该退位！

你说你造反合理？因为“一个民族，一个国家”，你只是追求皇汉民族的独立自主。那就只允许你皇汉民族独立自主？不允许我蒙古民族独立自主？那不成了“只许州官放火，不需百姓点灯”了。而且既然是共和，也应该遵循自愿，哪有强迫共和的。我不愿意跟你们共和不可以吗？我大蒙古国要自己独立为一个国家。

其实早在1911年（清宣统三年），就在皇汉民族武昌起义，南方十四省（甘肃、河南、直隶、山东四省在袁世凯的控制下）宣布独立，共建皇汉民族国家，成立中华民国的时候，外蒙古活佛八世哲布尊丹巴也在沙皇俄国的支持下，依据“一个民族，一个国家”的理论，在库伦宣布独立，建立“大蒙古国”政府，自称日光皇帝。

哲布尊丹巴，蒙古语也称为温都尔格根（高位光明者）、帕克托格根（圣光明者）或博克多格根，因此该大蒙古国也叫“博克多汗国”。哲布尊丹巴也被尊称为哲布尊丹巴呼图克图。呼图克图是清朝授予蒙、藏地区有德僧人的封号。“呼图克”为蒙语音译，是“寿”的意思，“图”是“有”的意思，合起来就是“有寿之人”或“有德之人”，俗称活佛。

也就是说，在满清宣布退位之前，南方中华民国已经独立，北方大蒙古国已经独立。后来南北议和，满清退位，南方取消独立，袁世凯出面组建五族共和的中华民国。但是大蒙古国并没有取消独立，五族共和的中华民国实际上只包括了内蒙古。中华民国不承认大蒙古国的独立，外蒙古不承认中华民国的统治。

大蒙古国是不是一个国家？成为一个国家的标准是什么？国家是什么？这个政治学概念存在多种定义，但是离不开三个构成要素：政权，土地和人民。需要得到别人的承认吗？需要得到全世界的承认吗？需要得到世界上最强大国家的承认吗？需要得到上一个政权的承认吗？1949年10月1日，中华人民共和国成立。全世界承认了吗？强大的美国承认了吗？上一个政权国民党承认了吗？都没有。但也不妨碍我们成立一个国家。

你外蒙古要独立，那汉蒙混居的内蒙古怎么办？外蒙古说，都叫蒙古，当然也归我了！于是想吞并内蒙古，袁世凯不同意了，出兵收复内蒙古，一打就打了三年。最终于1915年6月7日，中国北洋政府及外蒙自治当局与沙皇俄国在恰克图签订《中俄蒙协约》，又称恰克图协约。协约内容第二条：“外蒙古承认中国宗主权。中国、俄国承认外蒙古自治，为中国领土之一部分。”就这样在形式上取消了外蒙的“独立”，代之以“自治”，但是实际上外蒙仍处于独立状态。直到1919年，中华民国北洋政府将领徐树铮出兵占领外蒙古，才算勉强短暂的收复，但是很快由于国内军阀混战，外蒙古又脱离了控制。1924年11月26日，在苏联与第三国际支持与行动下，在中国及英、美等当时主要国家政府不予承认的情况下，蒙古人民党宣布废除君主立宪制，成立蒙古人民共和国，定都库伦，改城名为乌兰巴托，以1911年作独立纪元，再次独立。不过中国还是不愿意承认。直到1945年8月14日，经过长时间的谈判，国民党终于允许蒙古人民进行公投自行决定去留。1945年10月20日外蒙古开始举行公民投票，投票结果显示，参加的公民都赞成外蒙古从中国独立出去。1946年1月5日，中华民国正式承认蒙古人民共和国独立。

二战之后，由美国主导的西方国家，倡导人民自决权，那是源自1823年的门罗宣言，为了保护美洲人的美洲，1918年一战结束后，美国总统威尔逊提出的十四点和平建议，将人民自决权的适用范围推向全世界，不过未受列强重视，1941年英美发表大西洋宪章，再起草联合国宣言，阐明了人民自决权。殖民地的归属取向，是殖民地人民的选择。1946年，菲律宾公投选择独立，不再是美国的殖民地；1959年，夏威夷公投选择加入美利坚合众国，成为美国第五十个州；1960年，波多黎各公投选择不独立，继续作万恶米国的殖民地。

再来说说蒙古的亲家满清。
1912年2月12日，中国历史上最后一位皇帝，爱新觉罗•溥仪，于宣统三年十二月二十五日（农历），颁布退位诏书，宣布大清帝国统治的结束。那年，溥仪才6岁。
既然人家主动退位，当然不能亏待人家，于是给了丰厚的待遇，例如每年给他家多少多少生活费，例如北京一环内的房子产权归国家，使用权归他家，等等。（《关于大清皇帝辞位之后优待条件》）
1917年6月，张勋利用总统黎元洪与总理段祺瑞的矛盾，率领忠于满清的辫子军，借“调停”为名进京，把溥仪请出来继续当皇帝，宣布复辟满清。可惜复辟只闹了12天，就被镇压了。张勋逃入荷兰使馆，段祺瑞重新控制北京。那年，溥仪才12岁。

他只是个孩子啊！

这次复辟，能怪溥仪吗？一个没有行为能力的未成年少年。段祺瑞也是比较讲道理的，知道不能怪他，于是继续遵守当年的约定，每年还是给他家多少多少生活费，北京一环内的房子使用权还是归他家。

作为孩子的溥仪，就乖乖从龙椅上下来，回养心殿玩别的游戏去了。他以为他的人生可能就这样继续过下去了。直到1924年10月23日，冯玉祥突然发动北京政变，监禁总统曹锟，驱逐溥仪出宫。那年，溥仪19岁了。

不是说好的优待清室的吗？不是说好的给生活费的吗？不是说好的给房子住的吗？怎么统统都没有了？这些物质条件也就算了，你们还刨我们家祖坟！（1928年奉系军阀张宗昌下属孙殿英盗掘慈禧陵墓。）

如果你是溥仪，你是什么感受？作为一个热血汉子，你不想雪耻？你不想报仇？难道就不能像英国查理二世一样复辟？（清教徒护国公克伦威尔将天主教徒国王查理一世送上断头台，实行共和制。克伦威尔死后英国政坛混乱，国会迎回查理二世，复辟君主制，君主制一直持续到现在。）难道就不能像法国拿破仑三世一样复辟？（拿破仑滑铁卢失败，波旁王朝复辟，而后又被革命推翻，法国成立第二共和国，全民投票选举拿破仑三世成为总统，又全民投票选择拿破仑三世成为皇帝，第二帝国复辟。可惜普法战争输给了普鲁士，第二帝国就覆灭了。）你需要的，是一个机会。就在这时候有个怪叔叔笑呵呵地对你说：“来，小朋友，他们欺负你是他们不对，让我来实现你的愿望，带你回你祖先龙兴之地，重新建立一个帝国！”

1931年，日本发动“九一八事变”，侵占了东北三省。为更好地统治东北，日本迎回溥仪，扶持为代理人，1932年，建立满洲国，1934年，改国号为“满洲帝国”，改称“皇帝”。
溥仪会成为傀儡，他不知道吗？他知道，但是成为一个傀儡皇帝也比在天津当落魄皇帝强。他是汉奸吗？他是满人，怎么会是“汉”奸呢？他内心会愧疚吗？怎么可能！他心中有的是对我们违约的愤怒？

作为傀儡政权，满洲国被当作日本对亚洲国家发动侵略战争的帮凶，而不是被当作日本侵略奴役的受害者。因此1945年，苏联对日宣战后，红军进入东北，对待东北一点都不温柔。就不是来解放东北的，而是来打败满洲国的。后来同盟国胜利，对满洲国的态度并不是同情，而是当作战败国一样处理对待。

拿下东北的苏联，明面上是交接给国民党的，但是暗地里还是在支持共产党。一方面共产党动手也比较快，日本投降后直接派干部飞往东北交接，部队当地招募，而国民党是成建制的部队往东北开进，速度肯定慢半拍。另一方面，由于当时为了抵抗日本侵略，还处于第二次国共合作时期，此时共产党军队的编制还是国民革命军第十八集团军。因此把东北交给共产党的军队，等于交给了不听国民党中央指挥的国民革命军而已。不过这其实是狡辩，因为国民党1945年8月与苏联签订《中苏友好同盟条约》，以不干涉外蒙古独立为代价，换取苏联几个条件，其中就包括不缔结反对国民党的任何同盟，不参加反对国民党的任何集团，不干涉中国内政。这个反对国民党的，当然就是共产党了。支持共产党，其实已经违背了《中苏友好同盟条约》。
最后得到了东北的共产党，宛如刘秀得了河北，李渊得了关中，朱元璋得了江南，这才是共产党能统一中国的真正资本。

说实话，江西瑞金被蒋介石围剿了那么多次，最后还是不得已放弃了，才有了两万五千里长征。
而蒋介石在剿灭共产党的时候，也是有自己打算的。那就是借剿共的名义，尽量削弱非黄埔系的地方军阀。而每次反围剿斗争能胜利的关键，就是避开与实力强大的黄埔系部队正面冲突，打击实力较弱的地方军阀部队，从而突破包围圈，取得反围剿的胜利。
而长征过程也被蒋介石利用来削弱地方军阀。红军进入湖南，黄埔系部队就跟进湖南，从而削弱了地方军阀对湖南的控制力。红军想进入广西，李宗仁就是怕黄埔系部队跟着进广西，所以放过共产党，让共产党进入贵州，黄埔系部队就跟进贵州，贵州军阀就交权了。相当于共产党走了一圈，黄埔系部队跟了一圈，地方军阀收编了一圈，实现了对西南军阀的打击，强化了蒋介石的全国控制权。

共产党好不容易到了延安，形势也不见好，只是保住了星星之火。延安再被围剿几次，估计也守不住。经不住对手人多实力强啊。就算守住了，那穷山恶水又能养活多少部队人员？又能生产多少武器装备？

直到得到了东北，共产党才真正拥有了与国民党一决高下的实力。
而此时的东北，已经没人认为那只是属于满人的土地了，已经是中华民族的一份子了。


尽管我们与人为善，无愧于我们良心，坚持做一个好人，但是总有坏人当道，魔高一丈的时候。毕竟决定一时的胜负，还是要靠实力。那为什么我们还要坚持？不是因为我们期待好人好报的反馈，不是因为我们相信邪不胜正的结局，而是因为我们相信，坚持做一个好人，才是对的。


在经历了联姻、战争等和平的或非和平的融合之后，形成了今日的中华民族。

